import { JetBrains_Mono } from "next/font/google"; // Corrected import statement
import "./globals.css";

const jetbrainsMono = JetBrains_Mono({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800"], // Corrected the weight array
    variable: "--font-jetbrainsMono", // Fixed the variable assignment
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={jetbrainsMono.variable}>
                {children}
            </body>
        </html>
    );
}
